# Generated by Django 3.1 on 2020-09-09 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=128)),
                ('EmailAdress', models.EmailField(max_length=128)),
                ('Password', models.CharField(max_length=128)),
                ('PasswordConfirmation', models.CharField(max_length=128)),
                ('Img', models.ImageField(upload_to='images')),
            ],
        ),
    ]
