# Generated by Django 3.0.4 on 2020-09-14 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talk', models.CharField(max_length=10000)),
                ('time', models.DateTimeField()),
                ('person_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_from', to='myapp.User')),
                ('person_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_to', to='myapp.User')),
            ],
        ),
    ]
