# Generated by Django 3.1 on 2020-11-15 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='message',
            field=models.CharField(max_length=1000),
        ),
    ]
