# Generated by Django 3.1 on 2020-08-31 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200831_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='talk_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talk_from', to='myapp.user'),
        ),
        migrations.AlterField(
            model_name='talk',
            name='talk_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talk_to', to='myapp.user'),
        ),
    ]
