# Generated by Django 3.1 on 2021-10-26 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20211026_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='img',
            field=models.ImageField(default='asset/deeee.png', upload_to='img'),
        ),
    ]
