# Generated by Django 3.1 on 2020-09-20 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200919_0928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talk',
            name='date',
        ),
        migrations.AlterField(
            model_name='talk',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
