# Generated by Django 3.1 on 2021-08-21 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210821_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='icon',
            field=models.ImageField(default='images/noimage.png', upload_to='uploads', verbose_name='画像'),
        ),
    ]
