# Generated by Django 3.1 on 2020-09-22 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_headerimage_prof_msg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prof_msg',
            name='prof_msg',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
