# Generated by Django 3.0.4 on 2021-08-26 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_talk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='talk',
            old_name='pub_data',
            new_name='pub_date',
        ),
    ]
