# Generated by Django 3.2 on 2021-05-07 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0003_alter_talk_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='from_talk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_talk', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='talk',
            name='to_talk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_talk', to=settings.AUTH_USER_MODEL),
        ),
    ]
