# Generated by Django 3.1 on 2020-09-20 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20200920_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talk_recipient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='talk',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talk_sender', to=settings.AUTH_USER_MODEL),
        ),
    ]
