# Generated by Django 3.1 on 2021-11-17 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_message_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='friend',
            new_name='reciever',
        ),
    ]
