# Generated by Django 3.1 on 2020-09-02 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20200831_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='time',
            field=models.DateField(null=True),
        ),
    ]
