# Generated by Django 3.1 on 2020-10-04 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20201004_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hobby',
            field=models.ManyToManyField(blank=True, null=True, to='myapp.Hobby'),
        ),
    ]
