# Generated by Django 3.1 on 2021-05-21 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0005_auto_20210521_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='username',
        ),
        migrations.AddField(
            model_name='message',
            name='tousername',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to1', to=settings.AUTH_USER_MODEL),
        ),
    ]
