# Generated by Django 3.1 on 2020-09-07 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20200907_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='img',
            field=models.ImageField(default='image', upload_to='img/upload'),
            preserve_default=False,
        ),
    ]
