# Generated by Django 3.0.4 on 2021-05-30 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='images/', verbose_name='image'),
        ),
        migrations.DeleteModel(
            name='UserImage',
        ),
    ]
