# Generated by Django 3.1 on 2021-10-21 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20211021_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='friend',
        ),
    ]
