name: Django CI

on:
  push:
    branches: [ cicd-intro, master ]
  pull_request:
    branches: [ cicd-intro ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Docker Container Create
        run: |
          docker-compose up -d
    - name: Install Dependencies
      run: |
        docker-compose exec web python -m pip install --upgrade pip
        docker-compose exec web pip install -r requirements.txt
    - name: Run Tests
      run: |
        docker-compose exec web python manage.py test
    - name: Lint with black
      run: |
        docker-compose exec web pip install black
        docker-compose exec web black .
